server:
    port: 8080
logging:
    config: classpath:config/logback-spring.xml
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJCCWYiXeA7akkKvdNL3OvxsCr1AZ4zH3lBTuDz0QDogXmdAedRqG9PJQ2VXuFMbm3IeOvX2jRtZBfrSVtXYMMCAwEAAQ==
spring:
    application:
        name: stream-model-system
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stream_model?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true&serverTimezone=UTC
        username: root
        password: IGmQLbAO4IO+sXRRgFmIAXKgDsXF6fmi1skNMiU0m922ae6MIdpDjqGTEXdAl9DP7lOZ44bokx5Ma3zNVRnoew==
        druid:
            filter:
                config:
                    enabled: true
            connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
        filters: stat,log4j2,config
mybatis:
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: com.mowen.model